### ISSUE TITLE
Add event tracking

### ISSUE THREAD

**Issue by ASankaran** [HackIllinois/api-event#2]
- [x] Add `POST /event/track/` endpoint
    - [x] Return 200 if the specified user has successfully been marked as attending the specified event
    - [x] Return an unprocessable error if the event does not exist or if an error was encountered in adding the user to the list of attending users
    - [x] A user can only be marked as attending an event once
    - [x] A user can only be marked as attending an event if they have checked in

Request body for `POST /event/track/`:
```
{
    "event": "Example Event",
    "userid": "github000001"
}
```

- [x] Add `GET /event/track/event/{name}/` endpoint
    - [x] Return the list of userids marked as attending for the event with the specified `name`

Response body for `GET /event/track/event/{name}/`:
```
{
    "event": "Example Event",
    "userids": [
        "github000001",
        "github000002",
        "github000003"
    ]
}
```

- [x] Add `GET /event/track/user/{id}/` endpoint
    - [x] Return the list of events that the user with the given `id` was marked as attending

Response body for `GET /event/track/user/{id}/`:
```
{
    "userid": "github000001",
    "events": [
        "Example Event 1",
        "Example Event 2",
        "Example Event 3"
    ]
}
```

Quick lookups of tracking information are important for the `GET` endpoints. So tracking information should be stored as both `userid -> [event]` and `event -> [userid]` in two separate collections within the database.

It is important that the operations which modify the list of tracked users are done atomically, since many users will likely be marked as attending in concurrent requests.
